### ISSUE TITLE
Is this project not maintain?

### ISSUE THREAD

**Issue by busyfree** [bingoohuang/go-redis-web#3]
### fix the missing functions

![image](https://user-images.githubusercontent.com/504251/92069935-4e927d80-eddd-11ea-947c-73db38a788c3.png)

### run server, but webui like missing some features.
![image](https://user-images.githubusercontent.com/504251/92069846-070bf180-eddd-11ea-8e27-e3db86f9aec1.png)

**Comment by bingoohuang** [comment]
fixed
