### ISSUE TITLE
create default config error, use wrong file path variable

### ISSUE THREAD

**Issue by busyfree** [bingoohuang/go-redis-web#4]
Wrong code line
https://github.com/bingoohuang/redisweb/blob/13adf1496183552796bcc5ca440cc91714fb083c/flag.go#L65

Should be is 
```golang
		ioutil.WriteFile(appConfig.ConvenientConfigFile, []byte(`
```

**Comment by bingoohuang** [comment]
thanks, it is already fixed on code.
